#!/usr/bin/env bash

if [ ! -z "$WWWUSER" ]; then
    usermod -u $WWWUSER sail
fi

if [ ! -d /.composer ]; then
    mkdir /.composer
fi

chmod -R ugo+rw /.composer

if [ $# -gt 0 ]; then
    exec gosu $WWWUSER "$@"
else
    if [ ! -z "$DOCUMENT_ROOT" ]; then
        exec /usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.phpd.conf
    else
        exec /usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf
    fi
fi
